language: python
sudo: false

branches:
  only:
    - master

python:
  - 2.7
  - 3.5
  - 3.6
  - pypy

install:
  - pip install --upgrade pytest pytest-mock pytest-cov flake8
  - pip install -e .

script:
  - if [ "${TRAVIS_PULL_REQUEST}" == "true" ] && [ -z "$(git diff origin/master setup.py | grep '\+.*version=')" ]; then echo "Bump version in setup.py!"; exit 1; fi
  - flake8 src/ tests/
  - py.test -v --cov=./src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: borgstrom
  password:
    secure: "dAd8akgivw9fDGN1uRRQ6+t02SPtjYT9XSkExByAsXCaoa2bFpCFho5XZnkQn5u0fr8iurcI6zOFSuGyy8MUTl6euLHUAz3QzBr8bTOMVrenUErEQs9UxmrPU9kvW/JfAw5h3+ThJKjJI8EIsFH5CxDPxxkWHXQ4Ou0AKyIg0nJ/4ieOMzTTqUyBzhl9GYzpn3q+AYN9sJge0g3SJ1pxH+5zyLkLUw20uvR17UVhhsWk0CqyP8LS18uRcsejVCSQaq0GJwK/ToC7KKWH9pOqjo1DbDO1IIUu30RHz3hcRHesZV+RIEXuOp2DmkpQlKtxU2Ji0YEvDbCLQn748M2K1O58hox+TYi3McNtj1GazJ02OE7Sr8PXIMrYAqRF8GYDVXbxetPpD1mH4rbn55P6OCvdSlf7jCvMYw9vPK8rZxGYzR/v5u4zBL2oW+TMBBbeRVWhyW8vj1BPeV3GZU8a+o9tXOlzPyiiNHo71hJXHAUOVifbff936P3ZH3BeSQQwoz2LgAKWyBbka7tnQd0SdB+HMzt35PxnoJn82m7ZWvJTXMd3NGvHzIQ3Ry0oq1xAqTIN+1FJJQwHzNNkPpI2+ZWf7NnsfZXscMJQ3qHXfiZgN/DyvvXJC7SDPvwIL7nm1UjATnvqhPu8UL3xRz8OF6Fui5s7QpN6eugRbJW2XME="
  on:
    branch: master
  distributions: "sdist bdist_wheel"
