language: python
sudo: false

branches:
  only:
    - master

python:
  - 2.7
  - 3.5
  - 3.6
  - pypy

install:
  - pip install --upgrade pytest pytest-mock pytest-cov flake8
  - pip install -e .

script:
  - if [ "${TRAVIS_PULL_REQUEST}" == "true" ] && [ -z "$(git diff origin/master setup.py | grep '\+.*version=')" ]; then echo "Bump version in setup.py!"; exit 1; fi
  - flake8 src/ tests/
  - py.test -v --cov=./src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: borgstrom
  password:
    secure: "kwvEM078qMXNLc8pMxEBM7aGPcQwZ8p/lEhJ27QWBo1/cCMwFhwhY1L6C1siT7xwdcAd/rQSmmhsXxG4SQYHgZTSsFD1GD4D3ekttJEgihybuCszYfddFH4beALJd3yXTKRk390zqA2NPnjEz20Pf5gbCdfuBxHsAVgHMG1hAnGDaJF3xjmv95dE1HrxnoA0Vkk991jOr2EDyU64NR6gA7S51PxupoQ9h4SI87+/atcBbRNwxklqhI1EXxGw+5O4ByGO17KYFc2YEIKOzGp0mi9kGTk+s99jz458cJKC1zyPKr8MrsMACwBNbN9mEmMuK5bn1YkByt9RYMwe+EksYiMzJI0tYVaPa2JIgtfEwjAqBSLkWWGJqYphWVRk/tZ9LWxqLNqMPA7yjmOfcnKBYOUi4spRB0gW/occw4ySb4A2bshWeueveXDA7jnGSuYu4LKMdu3LVGhglL0mNcLVqKSBuU/EU7ulRqiyHebpHmQW2ae8Vvgpk9ogYBeDLTy1/Ul0o6pMNW26GllPTOH3prWczODXdf43NFysh/wgHSgl+gg65DpHXk2KCHk3SU4OhmgUDRocPdy0rBctYRo9Llh3n6+ACUkI1rHXCB2lu1LGmA7gjuKPPnqNg74U7SrvPn3TGqOmJp5uVW4a/vFdLwuqOnCf4BQzNu2OjvfbhOE="
  on:
    branch: master
  distributions: "sdist bdist_wheel"
